#!/bin/sh
#
# makesrcdist - make a source distribution of mxml.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating mxml-$version.tar.gz...
git archive --format tar --prefix=mxml-$version/ HEAD | gzip -v9 >mxml-$version.tar.gz
gpg --detach-sign mxml-$version.tar.gz

