#!/bin/sh
#
# makesrcdist - make a source distribution of mxml.
#

echo "Getting distribution..."

CVS_RSH=ssh; export CVS_RSH
MAINTAINER=mike

cd /tmp
cvs -q -d$MAINTAINER@tango.easysw.com:/development/cvs get mxml

if test $# = 0; then
	echo -n "Version number for distribution? "
	read version
else
	version=$1
fi

rm -rf mxml-$version
mv mxml mxml-$version
cd mxml-$version

if test x$version != xsnapshot; then
	echo "Tagging release..."

	tag=`echo v$version | tr '.' '_'`

	cvs tag -F $tag
fi

echo "Removing CVS directories..."

find . -name .cvsignore -exec rm -f '{}' \;
find . -name CVS -exec rm -rf '{}' \;

rm makesrcdist
rm -rf www

cd ..

echo "Making UNIX distribution..."

gtar czf mxml-$version.tar.gz mxml-$version

echo "Removing distribution directory..."

#rm -rf mxml-$version

echo "Done!"
